server {
    listen 80;
    server_name webmin.wasypro.com;
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    server_name webmin.wasypro.com;

    ssl_certificate     /etc/letsencrypt/live/app.wasypro.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.wasypro.com/privkey.pem;

    location / {
        proxy_pass https://127.0.0.1:10000;
        proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 90;
    }
}
