---
- name: "Install PostgreSQL and PostGIS"
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - postgis
    state: present

- name: "Ensure PostgreSQL service is enabled and started"
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: "Create erp master database user"
  become_user: postgres
  community.postgresql.postgresql_user:
    name: erp
    password: "erp_dev_2026"
    role_attr_flags: "SUPERUSER,LOGIN"
